create table if not exists public.public_music_tracks (
  id bigint generated by default as identity primary key,
  provider text not null default 'soundcloud',
  provider_track_id text not null,
  title text not null,
  artist text not null,
  cover_url text,
  audio_url text,
  source_url text,
  format text not null default 'SOUNDCLOUD',
  duration_sec integer not null default 0,
  position integer not null default 0,
  published_by text not null default 'jessew1lliams',
  created_at timestamptz not null default now()
);

create unique index if not exists ux_public_music_tracks_provider_track
  on public.public_music_tracks(provider, provider_track_id);

create index if not exists ix_public_music_tracks_position
  on public.public_music_tracks(position, created_at);

alter table public.public_music_tracks enable row level security;

drop policy if exists "public music select" on public.public_music_tracks;
create policy "public music select"
on public.public_music_tracks
for select
to anon, authenticated
using (true);

drop policy if exists "public music write" on public.public_music_tracks;
create policy "public music write"
on public.public_music_tracks
for all
to anon, authenticated
using (true)
with check (true);
